### ISSUE TITLE
As a car sharing operator I would like to have a new web-component for visualizing in real-time the availability of the cars on a map

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-web-components#39]
DEADLINE: 31.01.2022
- [x] @RudiThoeni / @Piiit  put again online the old widget on a temporary domain, e.g. deprecated.mobility.bz.it 

DEADLINE: 28.02.2022
- [x] @rcavaliere and @dulvui decide which web-component to adapt for this request
- [x] @dulvui implements the web-component, by following the look&feel of the current old widget, and makes this available on the web-components store
test link:
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/15a4b192-eb02-42e0-94e3-8f2aebf4e229
- [x] @rcavaliere manages the usage of the web-application by Car Sharing Alto Adige
- [x] @dulvui remind to shutdown the deprecated services (See https://github.com/noi-techpark/realtimebus-v2/issues/17)

**Comment by rcavaliere** [comment]
@dulvui do we have some issues with the web components store? I can not see anything if I click on the link of the car sharing web component now...

**Comment by dulvui** [comment]
@rcavaliere sorry for late reply, I didn't check github notifications for a while.
Yes we are migrating to v2 of the store and github actions so its currently now working. I'll inform you when its working again

**Comment by rcavaliere** [comment]
@dulvui ok please let me update. @Piiit is there a way to create a shortened link to a certain web-component through the store?

**Comment by Piiit** [comment]
@rcavaliere No, but you could use some external tool for that...

**Comment by rcavaliere** [comment]
@Piiit for example?

**Comment by Piiit** [comment]
https://tinyurl.com --> https://tinyurl.com/3c9kz44c

**Comment by rcavaliere** [comment]
@dulvui wonderful work, I tested it and works very well. Congratulations! I think we can put the web-component in production, i.e. in the productive web component store

**Comment by dulvui** [comment]
@rcavaliere Thank you! I'll put it to production next week and inform you when it's done.

**Comment by rcavaliere** [comment]
@dulvui @Piiit I think we can now proceed with https://github.com/noi-techpark/realtimebus-v2/issues/17. Please consider when we can schedule this, the advantage is to make a little bit of order of old / deprecated prototyping systems that we used in the past
