### ISSUE TITLE
As a project manager, I would like to see the new e-mobility web components deployed and reachable under the domains   webcomponents.opendatahub.bz.it/echarging-map/ and  webcomponents.opendatahub.bz.it/echarging-dashboard/

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-web-components#4]

**Comment by ohnewein** [comment]
Hi @bertolla ,

it looks great!

http://webcomponents.opendatahub.bz.it as a **very** alpha Web Component Store containing the first two components:

- http://webcomponents.opendatahub.bz.it/echarging-map/
- http://webcomponents.opendatahub.bz.it/echarging-dashboard/

@Piiit @niettadesantis @RudiThoeni 

Best
Patrick
