### ISSUE TITLE
As IDM I would like that the Specialannouncement Webcomponent in the Webcomponents store has only valid configuration fields.

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/odh-web-components#44]
- The articles inserted are available only in DE, IT and EN - so there should be only these 3 options in the language drop-down.
- Please remove "hide Articles with id (Array with strings)" (what is the use of it in our webcomponent?)

And: 
Can you please explain us why the articles are not updated immediatly in the webcomponent after they get modified in the data browser? How long does it take to have them updated? Here an example (ID: 38bf2bdfbcfa-6383-e3f1-3559-0913867d):

![image](https://user-images.githubusercontent.com/46811227/155513301-3c9ff121-0fcb-4f4f-8953-f2d3909496b9.png)

as you see, the link is not the one that was inserted this morning in the databrowser:

![image](https://user-images.githubusercontent.com/46811227/155513439-6f5e3816-f1cd-4ff1-9268-af5c31a6a313.png)

**Comment by RudiThoeni** [comment]
Hi Antonietta
I will put this into sprint todo, 
the Update i will check maybe the push is not well configured or there is a cache that does not show the changes immediately, i will check it

I will remove all not valid configuaration options like this hide Articles..... 
If you are ok i think we can make the rule every SpecialAnnouncement with ODHActive = true will be shown? ok? so i will set this also on the web component?

**Comment by niettadesantis** [comment]
That's fine, thank you Rudi!

**Comment by RudiThoeni** [comment]
ok checked there was caching active so the change was not seen immediately
I noticed that the push fires to fast, i have to add a little delay on pushing from raven instance to odh instance
