### ISSUE TITLE
As a company developing the new e-mobility web component, I would like to have examples of calls to the APIv2.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/odh-web-components#9]

**Comment by bertolla** [comment]
I took all possible queries from userstories and found some problems:
- show all echarging stations of bolzano
``

- show number of public, private and private with public access echarging stations
`https://ipchannels.integreen-life.bz.it/ninja/api/v2/flat/EChargingStation?limit=-1&offset=0&select=smetadata&where=sactive.eq.true&shownull=false&distinct=true`

- show the total number of plugs and how many are currentyl available
``

- filter EchargingPlugs by voltage
`https://ipchannels.integreen-life.bz.it/ninja/api/v2/flat/EChargingPlug?limit=-1&offset=0&select=*&where=sactive.eq.true&shownull=false&distinct=true`

- filter EchargingStations by payment method
`https://ipchannels.integreen-life.bz.it/ninja/api/v2/flat/EChargingPlug?limit=-1&offset=0&select=*&where=sactive.eq.true&shownull=false&distinct=true`

- filter EchargingStations by state
`https://ipchannels.integreen-life.bz.it/ninja/api/v2/flat/EChargingPlug?limit=-1&offset=0&select=*&where=sactive.eq.true&shownull=false&distinct=true`

**Comment by bertolla** [comment]
- Filters are not applicable to metadata and currently it would be the most desired feature. 
- The bounding box filter has a bug which should get fixed to make the first query work
https://github.com/noi-techpark/bdp-core/issues/111

**Comment by bertolla** [comment]
@rcavaliere I noted this userstory in Belkas Jira
> Come [Utente] voglio filtrare le colonnine per  "METODO DI PAGAMENTO"

but we unfortunately don't have this info, just an URL.

**Comment by rcavaliere** [comment]
@bertolla OK if it is like this please provide this info in the correspondent user story in Belka's JIRA. We won't implement this functionality.

**Comment by bertolla** [comment]
I put you as  tester, but let's wait for Belka to respond

**Comment by rcavaliere** [comment]
No feedback for now due to the repo structure discussion, let's keep this issue open under "testing".

**Comment by Piiit** [comment]
@rcavaliere The discussion is over, and the new ninja is online.
